# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

enabled_platforms=fabric,neoforge

# Mod Properties
archives_base_name=servui
mod_version=1.9.1
maven_group=co.lemee

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.10
#yarnVersion=1.21.10+build.1
fabric_loader_version=0.16.14

#Fabric api
fabric_version=0.138.4

# Dependencies
neoforge_version=21.10.64
