modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/jblemee/servui/issues"
license="LGPLv3"

[[mods]]
modId="servui"
version="${version}"
displayName="ServUI"
displayURL="https://github.com/jblemee/servui/releases"
logoFile="icon.png"
authors="Patbox,aws404,lemee"
description='''Library for creating server side guis!'''
displayTest="IGNORE_ALL_VERSION"

[[mixins]]
    config="servui.mixins.json"

[[mixins]]
    config="servui.neoforge.mixins.json"

[[dependencies.servui]]
    modId="neoforge"
    type="required"
    versionRange="[21.10,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.servui]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.10,)"
    ordering="NONE"
    side="BOTH"
